//
// JSONDataEncoding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire

public struct AlamofireJSONDataEncoding: ParameterEncoding {

    // MARK: Encoding

    /// Creates a URL request by encoding parameters and applying them onto an existing request.
    ///
    /// - parameter urlRequest: The request to have parameters applied.
    /// - parameter parameters: The parameters to apply. This should have a single key/value
    ///                         pair with "jsonData" as the key and a Data object as the value.
    ///
    /// - throws: An `Error` if the encoding process encounters an error.
    ///
    /// - returns: The encoded request.
    public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
        
        let urlRequest = try urlRequest.asURLRequest()
        
        let jsonDataEncoding = JSONDataEncoding()
        
        return jsonDataEncoding.encode(urlRequest, with: parameters)
    }

    public static func encodingParameters(jsonData: Data?) -> Parameters? {
        return JSONDataEncoding.encodingParameters(jsonData: jsonData)
    }

}
